
# Purpose: to guide the process for modelling use
# Author: Xiao Jing Guo (xiaojing.guo@nrcan-rncan.gc.ca)
# Date: 2025-02-10

# # # # # step 0: downloading the CFSTRenD package using remotes package,

# install remotes package first
if (!require("remotes", quietly = TRUE)) {
  install.packages("remotes")
}

# as the package is still under development, it's a good practice to run the installation frequently
remotes::install_github("CFS-treering/CFSTRenD")

# # # # # # # # # # # # # # # # # # # # end step 0 # # # # # # # # # # # # # # # # # # # #




# # # # # step 1: loading package

library(data.table)
library(CFSTRenD)

# # # # # # # # # # # # # # # # # # # # end step 1 # # # # # # # # # # # # # # # # # # # #



# # # # # step 2: reading your own data

# an example dataset stored in the package
# tree ring data
samples69.o <- fread(system.file("extdata", "samples69.csv", package = "CFSTRenD"))
# climate data
clim69 <- fread(system.file("extdata", "clim69.csv", package = "CFSTRenD"))

# # # # # # # # # # # # # # # # # # # # end step 2 # # # # # # # # # # # # # # # # # # # #



# # # # # step 3: transforming the source data into standard format

# arguments of the function
# data is a list, the first item is the a data table in wide format including both meta and ring width measurement(mm);
#                 the second item is a flat sequence referring to the column indices of ring width measurement variables
# usage = 2 to generate CFSTRenD data format for data reporting.
# out.csv, default is NULL, otherwise to specify the directory to output the csv files of 7 tables, tr_all_wide and complete_vars.

# notes:
# You may be required to re-run the CFS_format function multiple times to provide the information of mandatory variables, by adding new columns or rename the existing columns.
# for example, if you only have tree_id in your data, you need to assign the value of tree_id to sample_id and radius_id to conform to the CFSTRenD data structure.
# Please follow the prompted messages carefully while running the function.


# no csv output
samples69.trt <- CFS_format(data = list(samples69.o, 39:140), usage = 2, out.csv = NULL)

# output the files to the directory c:/tmp/sample69
samples69.trt <- CFS_format(data = list(samples69.o, 39:140), usage = 2, out.csv = "c:/tmp/sample69")

# # # # # # # # # # # # # # # # # # # # end step 3 # # # # # # # # # # # # # # # # # # # #




# # # # # step 4: generating data report
# arguments of the function
# robj is an R object, generated by CFS_format function;
# usage = 2, generating data report for modelling use
# output_file, default is NULL, otherwise to specify the directory/filename to output the html file.

generate_report(robj = samples69.trt, usage = 2, output_file = NULL)

# # # # # # # # # # # # # # # # # # # # end step 4 # # # # # # # # # # # # # # # # # # # #


# # # # # step 5: modelling

# CFSTRenD package provides 4 functions to analyze the data at different spatial levels.
  # gamm_radius(): radii
  # gamm_site(): data within 1 site
  # gamm_spatial(): data with multiple sites
  # bam_spatial(): large dataset
# the arguments of the 4 functions are similar, requiring data and m.candidates,
# all 4 functions allow to model the response variable in original scale and log-scale

# radii
series.i <- samples69.trt$tr_all_long$tr_7_ring_widths[uid_radius == 1]

# log-scale is default, the default will be changed to original scale in the future.
m.radius.log <- gamm_radius(data = series.i, resp_scale = "log", m.candidates = "rw_mm ~ s(year)" )

# original scale, as long as resp_scale not equals to "log"
m.radius <- gamm_radius(data = series.i, resp_scale = "", m.candidates = "rw_mm ~ s(year)" )
m.radius.log <- gamm_radius(data = series.i, resp_scale = "log", m.candidates = "rw_mm ~ s(year)" )
# generate the model report

# view the report
generate_report(m.radius, output_file =  NULL)
generate_report(m.radius.log, output_file =  NULL)

# save the report to html
generate_report(m.radius, output_file =  "c:/tmp/sample69/model_report 1radius.html")

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #


# 1 site

# merge with climate variable
samples69_clim <- merge(samples69.trt$tr_all_wide[, c("uid_site", "site_id","latitude", "longitude",  "species", "uid_tree", "uid_radius")], samples69.trt$tr_all_long$tr_7_ring_widths, by = "uid_radius")

# # Calculate BAI
samples69_clim <- cal.bai(samples69_clim, "uid_radius", "rw_mm")

samples69_clim <- merge(samples69_clim, clim69, by = c("site_id", "year"))


setorder(samples69_clim, uid_tree, year)
# choose 1 site, ignore the first 10 years as Girardin 2022
site.i <- samples69_clim[uid_site == 10][ageC > 10]
m.site <- gamm_site(data = site.i,
                    m.candidates =   "bai_cm2 ~ log(ba_cm2_t_1) + s(ageC) + FFD"
)

# generate the model report
generate_report(m.site, output_file =  "c:/tmp/sample69/model_report 1site.html")

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #


# multiple sites
site.mul <-samples69_clim[uid_site <= 10][ageC > 10]
m.spatial <- gamm_spatial(data = site.mul,
                    m.candidates =   "bai_cm2 ~ log(ba_cm2_t_1) + s(ageC) + FFD"
)

# generate the model report
generate_report(m.spatial, output_file =  "c:/tmp/sample69/model_report multi-sites.html")

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #


# large dataset
site.vast <-samples69_clim[ageC > 10]
bam.spatial <- bam_spatial(data = site.vast,
                          m.candidates =   "bai_cm2 ~ log(ba_cm2_t_1) + s(ageC) + FFD"
)

# generate the model report
generate_report(bam.spatial, output_file =  "c:/tmp/sample69/model_report large-data.html")

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #


# model selection, take the example of per site.
m.site.sel <- gamm_site(data = site.i,
                    m.candidates = c(
                      "bai_cm2 ~ log(ba_cm2_t_1) + s(ageC)",
                      "bai_cm2 ~ log(ba_cm2_t_1) + s(ageC) + FFD",
                      "bai_cm2 ~ log(ba_cm2_t_1) + s(ageC) + s(FFD)"

                    )
)


generate_report(m.site.sel, output_file = "c:/tmp/sample69/model_report selection.html")


# # # # # # # # # # # # # # # # # # # # end step 5 # # # # # # # # # # # # # # # # # # # #
