
# Purpose: to guide the data process for data submission use
# Author: Xiao Jing Guo (xiaojing.guo@nrcan-rncan.gc.ca)
# Date: 2025-02-10


# # # # # step 0: downloading the CFSTRenD package using remotes package,

# install remotes package first
if (!require("remotes", quietly = TRUE)) {
  install.packages("remotes")
}

# as the package is still under development, it's a good practice to run the installation frequently
remotes::install_github("CFS-treering/CFSTRenD")

# # # # # # # # # # # # # # # # # # # # end step 0 # # # # # # # # # # # # # # # # # # # #




# # # # # step 1: loading package

library(data.table)
library(CFSTRenD)

# # # # # # # # # # # # # # # # # # # # end step 1 # # # # # # # # # # # # # # # # # # # #



# # # # # step 2: reading your own data

# an example dataset stored in the package
samples69.o <- fread(system.file("extdata", "samples69.csv", package = "CFSTRenD"))

# # # # # # # # # # # # # # # # # # # # end step 2 # # # # # # # # # # # # # # # # # # # #



# # # # # step 3: transforming the source data into standard format

# arguments of the function
  # data is a list, the first item is the a data table in wide format including both meta and ring width measurement(mm);
  #                 the second item is a flat sequence referring to the column indices of ring width measurement variables
  # usage = 1 for going through the phase 1 QC check for data submission.
  # out.csv, default is NULL, otherwise to specify the directory to output the csv files of 7 tables, tr_all_wide and complete_vars.

# notes:
  # You may be required to re-run the CFS_format function multiple times to provide the information of mandatory variables, by adding new columns or rename the existing columns.
  # for example, if you only have tree_id in your data, you need to assign the value of tree_id to sample_id and radius_id to conform to the CFSTRenD data structure.
  # Please follow the prompted messages carefully while running the function.

# no csv output
samples69.trt <- CFS_format(data = list(samples69.o, 39:140), usage = 1, out.csv = NULL)

# output the files to your chosen directory, for example:  c:/tmp/sample69
samples69.trt <- CFS_format(data = list(samples69.o, 39:140), usage = 1, out.csv = "c:/tmp/sample69")



# # # # # # # # # # # # # # # # # # # # end step 3 # # # # # # # # # # # # # # # # # # # #




# # # # # step 4: generating complete data report
# arguments of the function
  # robj is an R object, generated by CFS_format function;
  # usage = 1, generating complete data report for data submission.
  # output_file, default is NULL, otherwise to specify the directory/filename to output the html file.


# view the report
generate_report(robj = samples69.trt, usage = 1, output_file = NULL)

# save the report to your chosen directory/filename, for example: c:/tmp/sample69/data_report.html
generate_report(robj = samples69.trt, usage = 1, output_file = "c:/tmp/sample69/data_report.html")

# # # # # # # # # # # # # # # # # # # # end step 4 # # # # # # # # # # # # # # # # # # # #




# # # # # step 5: submitting the data

# if something unusual is detected you may need to validate/correct it and re-run the procedure step 2 to step 4.
# if everything is fine, submit the data following the CFS-TRenD data submission procedure.
  # Until further notice, you need to put your data generated by CFS_format() in the directory \\s-que-dfs\dfs\Canada_Tree-Ring_Data\data_submission
  # and inform me by email xiaojing.guo@nrcan-rncan.gc.ca

# # # # # # # # # # # # # # # # # # # # end step 5 # # # # # # # # # # # # # # # # # # # #
